import {A1_BUILDER_PROGRESS_KEY,A1_BUILDER_SKILLS,A1_BUILDER_TASKS,validateA1BuilderBank} from "./a1-builder-data.js";
const QUOTAS={"basic-word-order":2,"verb-position-2":1,"time-first":2,"separable-verbs":1,"modal-structure":2,questions:2,negation:1,"case-chunks":1};
const shuffle=input=>{const result=[...input];for(let i=result.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[result[i],result[j]]=[result[j],result[i]];}return result;};
const create=(tag,className,text)=>{const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node;};
const readProgress=()=>{try{return JSON.parse(localStorage.getItem(A1_BUILDER_PROGRESS_KEY)||"null")||{};}catch{return {};}};
const sameOrder=(left,right)=>left.length===right.length&&left.every((token,index)=>token===right[index]);
function shuffledTiles(task){const tiles=task.words.map((text,index)=>({id:`${task.id}-token-${index+1}`,text,index}));let result=shuffle(tiles);for(let attempt=0;attempt<12&&task.acceptedAnswers.some(answer=>sameOrder(result.map(tile=>tile.text),answer));attempt++)result=shuffle(tiles);if(task.acceptedAnswers.some(answer=>sameOrder(result.map(tile=>tile.text),answer)))result=[...tiles.slice(1),tiles[0]];return result;}
export function createA1BuilderSession(previousIds=[],skills=null,limit=12){const previous=new Set(previousIds),selected=[];const quotas=skills?.length?Object.fromEntries(skills.map(skill=>[skill,Math.ceil(limit/skills.length)])):QUOTAS;Object.entries(quotas).forEach(([skill,count])=>{const pool=A1_BUILDER_TASKS.filter(task=>task.skill===skill),fresh=shuffle(pool.filter(task=>!previous.has(task.id))),fallback=shuffle(pool.filter(task=>previous.has(task.id)));selected.push(...[...fresh,...fallback].slice(0,count));});if(selected.length<limit)selected.push(...shuffle(A1_BUILDER_TASKS.filter(task=>(!skills||skills.includes(task.skill))&&!selected.some(item=>item.id===task.id))).slice(0,limit-selected.length));return shuffle(selected.slice(0,limit)).map(task=>({...task,tiles:shuffledTiles(task)}));}
export function updateBuilderCard(){const card=document.querySelector("[data-a1-builder]");if(!card)return;const count=card.querySelector("[data-builder-count]");if(count)count.textContent=`${A1_BUILDER_TASKS.length} Tasks · 12 per Session`;const status=card.querySelector("[data-builder-status]");if(!status)return;const progress=readProgress();status.textContent=progress.sessionsCompleted?`Best: ${progress.bestIndependent||0} / 12 Independent`:"Not Started";}

export function initA1Builder(setSharedPage){
 const $=id=>document.getElementById(id),errors=validateA1BuilderBank();if(errors.length){console.error("A1 Sentence Builder validation failed.",errors);$("practiceForm").textContent="Sentence Builder is temporarily unavailable because its local task data could not be validated.";$("submitPractice").hidden=true;return;}
 let progress=readProgress();const validTaskIds=new Set(A1_BUILDER_TASKS.map(task=>task.id));progress.skillStats=Object.fromEntries(Object.entries(progress.skillStats||{}).filter(([skill])=>A1_BUILDER_SKILLS[skill]));progress.taskStats=Object.fromEntries(Object.entries(progress.taskStats||{}).filter(([id])=>validTaskIds.has(id)));progress.lastSessionIds=Array.isArray(progress.lastSessionIds)?progress.lastSessionIds.filter(id=>validTaskIds.has(id)):[];let session=[],index=0,available=[],placed=[],history=[],attempts=0,hints=0,completed=false,status="",results=[],difficult=[],resultSaved=false,currentMode="balanced";
 setSharedPage("A1 Sentence Builder","Build correct German sentences by arranging word and phrase tiles. Use Undo, Reset or a limited Hint before checking.");$("practiceType").textContent="Writing";$("questionCount").textContent=`${A1_BUILDER_TASKS.length} local tasks · 12 per session`;$("submitPractice").hidden=true;$("practiceResult").setAttribute("aria-live","polite");document.querySelector(".practice-sheet")?.classList.add("builder-sheet");const help=document.querySelector(".practice-help");if(help){help.querySelector("h2").textContent="Build, check and improve";help.querySelector("p").textContent="Tap tiles to build the sentence. Tap a placed tile to return it, or use Undo and Reset. Check only after every tile is placed.";}
 const persist=()=>{progress.lastActivity=new Date().toISOString();localStorage.setItem(A1_BUILDER_PROGRESS_KEY,JSON.stringify(progress));};
 const task=()=>session[index];
 function startSession(skills=null,customIds=null){currentMode=skills?.length||customIds?"focused":"balanced";session=customIds?shuffle(customIds.map(id=>A1_BUILDER_TASKS.find(item=>item.id===id)).filter(Boolean)).slice(0,8).map(item=>({...item,tiles:shuffledTiles(item)})):createA1BuilderSession(progress.lastSessionIds||[],skills,skills?.length?8:12);index=0;results=[];difficult=[];resultSaved=false;$("practiceResult").hidden=true;$("practiceForm").hidden=false;beginTask();}
 function beginTask(){available=[...task().tiles];placed=[];history=[];attempts=0;hints=0;completed=false;status="";render();}
 function moveToPlaced(id){if(completed)return;const tile=available.find(item=>item.id===id);if(!tile)return;available=available.filter(item=>item.id!==id);placed.push(tile);history.push(id);status="";render();}
 function moveToAvailable(id){if(completed)return;const tile=placed.find(item=>item.id===id);if(!tile)return;placed=placed.filter(item=>item.id!==id);available.push(tile);history=history.filter(item=>item!==id);status="";render();}
 function undo(){const id=history.pop();if(!id)return;const tile=placed.find(item=>item.id===id);placed=placed.filter(item=>item.id!==id);available.push(tile);status="";render();}
 function reset(){available=[...task().tiles];placed=[];history=[];status="";render();}
 function useHint(){if(completed)return;const answer=task().acceptedAnswers[0],nextText=answer[placed.length];if(nextText===undefined)return;const candidate=available.find(tile=>tile.text===nextText);if(!candidate){status=`Hint: the next intended chunk is “${nextText}”.`;render();return;}hints++;moveToPlaced(candidate.id);status=`Hint placed: ${nextText}`;render();}
 function isCorrect(){const built=placed.map(tile=>tile.text);return task().acceptedAnswers.some(answer=>sameOrder(built,answer));}
 function check(){if(placed.length!==task().words.length){status="Use all the words first. সব শব্দ ব্যবহার করুন।";render();return;}attempts++;if(isCorrect()){complete(attempts===1&&hints===0?"independent":"retry");return;}status=attempts===1?"Not quite. Review the order and try again.":"Still not correct. Try again or show the solution.";difficult.push(task().id);render();}
 function showSolution(){const answer=task().acceptedAnswers[0];placed=answer.map((text,index)=>({id:`${task().id}-solution-${index}`,text,index}));available=[];complete("assisted");}
 function complete(resultStatus){completed=true;const item={task:task(),status:resultStatus,attempts,hints};results.push(item);const old=progress.taskStats[task().id]||{attempts:0,independent:0,retry:0,assisted:0,hints:0};progress.taskStats[task().id]={...old,attempts:old.attempts+1,[resultStatus]:(old[resultStatus]||0)+1,hints:old.hints+hints,lastPractised:new Date().toISOString()};const skill=progress.skillStats[task().skill]||{attempted:0,independent:0,retry:0,assisted:0};progress.skillStats[task().skill]={...skill,attempted:skill.attempted+1,[resultStatus]:(skill[resultStatus]||0)+1};progress.tasksCompleted=(progress.tasksCompleted||0)+1;if(resultStatus!=="independent")difficult.push(task().id);persist();render();}
 function displaySentence(){if(!placed.length)return"Your sentence will appear here.";const text=placed.map(tile=>tile.text).join(" ");return `${text}${task().skill==="questions"?"?":"."}`;}
 function render(){const current=task(),form=$("practiceForm");form.replaceChildren();const header=create("div","builder-task-header");header.append(create("span","builder-skill",A1_BUILDER_SKILLS[current.skill].title),create("strong","",`Task ${index+1} of ${session.length}`),create("span","",current.difficulty));const track=create("div","progress-track");const fill=create("i");fill.style.width=`${index/session.length*100}%`;track.append(fill);const instruction=create("section","builder-instruction");instruction.append(create("h2","",current.instructionEn));const bn=create("p","",current.instructionBn);bn.lang="bn";instruction.append(bn);const sentenceArea=create("section",`builder-sentence-area${completed?" is-complete":""}`);sentenceArea.append(create("span","","Your Sentence"));const built=create("div","builder-placed");if(!placed.length)built.append(create("p","builder-placeholder","Tap words below to start."));placed.forEach(tile=>{const button=create("button","builder-tile placed-tile",tile.text);button.type="button";button.lang="de";button.disabled=completed;button.setAttribute("aria-label",`Placed tile ${tile.text}. Activate to return it to the word bank.`);button.addEventListener("click",()=>moveToAvailable(tile.id));built.append(button);});sentenceArea.append(built,create("p","builder-sentence-preview",displaySentence()));const bank=create("section","builder-word-bank");bank.append(create("span","","Word Bank"));const tiles=create("div","builder-available");available.forEach(tile=>{const button=create("button","builder-tile",tile.text);button.type="button";button.lang="de";button.setAttribute("aria-label",`Available word tile: ${tile.text}`);button.addEventListener("click",()=>moveToPlaced(tile.id));tiles.append(button);});bank.append(tiles);const tools=create("div","builder-tools");[["Undo",undo,history.length===0],["Reset",reset,placed.length===0],["Hint",useHint,completed||!available.length]].forEach(([label,handler,disabled])=>{const button=create("button","challenge-secondary",label);button.type="button";button.disabled=disabled;button.addEventListener("click",handler);tools.append(button);});const live=create("p","builder-live",status);live.setAttribute("aria-live","polite");form.append(header,track,instruction,sentenceArea,bank,tools,live);
  if(!completed){const checkButton=create("button","builder-check","Check Sentence");checkButton.type="button";checkButton.disabled=placed.length!==current.words.length;checkButton.addEventListener("click",check);form.append(checkButton);if(attempts>=2){const solution=create("button","builder-solution","Show Solution");solution.type="button";solution.addEventListener("click",showSolution);form.append(solution);}}else{const feedback=create("section",`builder-feedback status-${results.at(-1).status}`);const label=results.at(-1).status==="independent"?"✓ Correct · Independent":results.at(-1).status==="retry"?"✓ Correct after retry":"Solution shown · Assisted";feedback.append(create("h2","",label));const sentence=create("p","builder-correct-sentence",current.sentence);sentence.lang="de";const exp=create("p","",current.explanationEn),expBn=create("p","builder-explanation-bn",current.explanationBn);expBn.lang="bn";const link=create("a","challenge-topic-link",`Review ${A1_BUILDER_SKILLS[current.skill].title} →`);link.href=`../library-topic/?level=A1&topic=${current.relatedTopic}`;feedback.append(sentence,create("strong","","Rule"),create("p","",current.rule),exp,expBn,link);const next=create("button","builder-next",index===session.length-1?"View Session Results":"Next Task →");next.type="button";next.addEventListener("click",()=>{if(index===session.length-1)showResults();else{index++;beginTask();}});feedback.append(next);form.append(feedback);}
  $("answeredCount").textContent=`${index} of ${session.length} completed`;$("progressFill").style.width=`${index/session.length*100}%`;
 }
 function breakdown(){return Object.keys(A1_BUILDER_SKILLS).map(skill=>{const rows=results.filter(row=>row.task.skill===skill);return{skill,total:rows.length,independent:rows.filter(row=>row.status==="independent").length};}).filter(row=>row.total);}
 function weakSkills(){return Object.entries(progress.skillStats).filter(([,stat])=>stat.attempted>=4&&stat.independent/stat.attempted<.75).sort((a,b)=>a[1].independent/a[1].attempted-b[1].independent/b[1].attempted).slice(0,2).map(([skill])=>skill);}
 function showResults(){const independent=results.filter(row=>row.status==="independent").length,retry=results.filter(row=>row.status==="retry").length,assisted=results.filter(row=>row.status==="assisted").length;if(!resultSaved){progress.sessionsCompleted=(progress.sessionsCompleted||0)+1;progress.bestIndependent=Math.max(progress.bestIndependent||0,independent);progress.lastSessionIds=session.map(item=>item.id);resultSaved=true;persist();}$("practiceForm").hidden=true;const result=$("practiceResult");result.hidden=false;result.replaceChildren(create("span","",currentMode==="focused"?"Focused Practice Complete":"Sentence Builder Session Complete"),create("strong","",`${session.length} tasks built`),create("p","builder-result-label",`Independent ${independent} · Retry ${retry} · Assisted ${assisted}`));const grid=create("div","builder-breakdown");breakdown().forEach(row=>{const card=create("div",row.independent/row.total>=.75?"is-strong":"needs-review");card.append(create("strong","",A1_BUILDER_SKILLS[row.skill].title),create("span","",`${row.independent} / ${row.total} independent`));grid.append(card);});const actions=create("div","builder-result-actions"),difficultIds=[...new Set(difficult)].slice(0,8);const review=create("button","","Review Difficult Sentences");review.type="button";review.disabled=!difficultIds.length;review.addEventListener("click",()=>startSession(null,difficultIds));const focus=weakSkills().length?weakSkills():breakdown().filter(row=>row.independent/row.total<.75).slice(0,2).map(row=>row.skill);const weak=create("button","","Practice Weak Areas");weak.type="button";weak.disabled=!focus.length;weak.addEventListener("click",()=>startSession(focus));const again=create("button","","New Builder Session");again.type="button";again.addEventListener("click",()=>startSession());const back=create("a","challenge-back-link","Back to Practice Center");back.href="../a1/#exercises";actions.append(review,weak,again,back);result.append(grid,actions);result.scrollIntoView({behavior:"smooth",block:"start"});}
 startSession();
}
