import { A1_READING_PROGRESS_KEY, A1_READING_SKILLS, A1_READING_TEXTS, validateA1ReadingBank } from "./a1-reading-data.js";
const shuffle=input=>{const result=[...input];for(let i=result.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[result[i],result[j]]=[result[j],result[i]];}return result;};
const create=(tag,className,text)=>{const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node;};
const readProgress=()=>{try{return JSON.parse(localStorage.getItem(A1_READING_PROGRESS_KEY)||"null")||{};}catch{return {};}};
const shuffledText=text=>({...text,questions:text.questions.map(question=>{const correct=question.options[question.answer],options=shuffle(question.options);return {...question,options,answer:options.indexOf(correct)};})});
export function createA1ReadingSession(previousIds=[],skills=null,limit=4){const previous=new Set(previousIds),active=skills?.length?skills:Object.keys(A1_READING_SKILLS),selected=[];const ordered=skills?.length?active:shuffle(active);for(const skill of ordered){const pool=A1_READING_TEXTS.filter(text=>text.skill===skill),fresh=shuffle(pool.filter(text=>!previous.has(text.id))),fallback=shuffle(pool.filter(text=>previous.has(text.id)));const candidate=[...fresh,...fallback].find(text=>!selected.some(item=>item.id===text.id));if(candidate)selected.push(candidate);if(selected.length===limit)break;}if(selected.length<limit)selected.push(...shuffle(A1_READING_TEXTS.filter(text=>active.includes(text.skill)&&!selected.some(item=>item.id===text.id))).slice(0,limit-selected.length));return shuffle(selected).map(shuffledText);}

export function updateReadingCard(){const card=document.querySelector("[data-a1-reading]");if(!card)return;const count=card.querySelector("[data-reading-count]");if(count)count.textContent=`${A1_READING_TEXTS.length} Reading Texts · 4 per Session`;const status=card.querySelector("[data-reading-status]");if(!status)return;const progress=readProgress();status.textContent=progress.sessionsCompleted?`Best: ${progress.bestPercent||0}%`:"Not Started";}

export function initA1Reading(setSharedPage){
 const $=id=>document.getElementById(id),errors=validateA1ReadingBank();if(errors.length){console.error("A1 reading bank validation failed.",errors);$("practiceForm").textContent="Reading is temporarily unavailable because its local text data could not be validated.";$("submitPractice").hidden=true;return;}
 let progress=readProgress();const validTextIds=new Set(A1_READING_TEXTS.map(text=>text.id));progress.skillStats=Object.fromEntries(Object.entries(progress.skillStats||{}).filter(([skill])=>A1_READING_SKILLS[skill]));progress.textStats=Object.fromEntries(Object.entries(progress.textStats||{}).filter(([id])=>validTextIds.has(id)));progress.lastSessionIds=Array.isArray(progress.lastSessionIds)?progress.lastSessionIds.filter(id=>validTextIds.has(id)):[];let session=[],index=0,answers=[],checked=false,results=[],mistakes=[],resultSaved=false,currentMode="balanced";
 setSharedPage("A1 Reading Practice","Read one realistic German text at a time, answer all its questions, then check the evidence and bilingual explanations.");$("practiceType").textContent="Reading";$("questionCount").textContent=`${A1_READING_TEXTS.length} local texts · 4 per session`;$("submitPractice").hidden=true;$("practiceResult").setAttribute("aria-live","polite");document.querySelector(".practice-sheet")?.classList.add("reading-sheet");
 const help=document.querySelector(".practice-help");if(help){help.querySelector("h2").textContent="Read · Answer · Check evidence";help.querySelector("p").textContent="Read the complete German text, answer every question for that text, then check your answers. Word Help stays optional and never reveals a full translation.";}
 const persist=()=>{progress.lastActivity=new Date().toISOString();localStorage.setItem(A1_READING_PROGRESS_KEY,JSON.stringify(progress));};
 function startSession(skills=null){currentMode=skills?.length?"weak":"balanced";session=createA1ReadingSession(progress.lastSessionIds||[],skills,skills?.length?Math.min(3,skills.length+1):4);index=0;answers=[];checked=false;results=[];mistakes=[];resultSaved=false;$("practiceResult").hidden=true;$("practiceForm").hidden=false;renderText();}
 function formatLabel(format){return format.replaceAll("-"," ").replace(/\b\w/g,letter=>letter.toUpperCase());}
 function renderReadingPanel(text){const panel=create("article",`reading-text-panel format-${text.format}`);panel.append(create("span","reading-format",`${formatLabel(text.format)} · Practice Example`),create("h2","",text.title));const content=create("p","reading-german-text",text.text);content.lang="de";panel.append(content);const details=document.createElement("details");details.className="reading-word-help";const summary=create("summary","","Need a word? · Word Help");details.append(summary);const list=create("dl");text.vocabularyHelp.forEach(item=>{const term=create("dt","",item.german);term.lang="de";const meaning=create("dd","",`${item.english} · ${item.bengali}`);meaning.lang="bn";list.append(term,meaning);});details.append(list);panel.append(details);return panel;}
 function renderText(){const text=session[index],form=$("practiceForm");form.replaceChildren();const header=create("div","reading-task-header");header.append(create("span","reading-skill",A1_READING_SKILLS[text.skill]),create("strong","",`Text ${index+1} of ${session.length}`),create("span","reading-answer-count",`${answers.filter(value=>value!==null&&value!==undefined).length} / ${text.questions.length} answered`));const track=create("div","progress-track");const fill=create("i");fill.style.width=`${index/session.length*100}%`;track.append(fill);const layout=create("div","reading-layout");layout.append(renderReadingPanel(text));const questions=create("section","reading-questions");questions.append(create("h2","","Comprehension Questions"));text.questions.forEach((question,qIndex)=>{const fieldset=create("fieldset",`reading-question${checked?(answers[qIndex]===question.answer?" is-correct":" is-wrong"):""}`);const legend=create("legend","",`${qIndex+1}. ${question.promptEn}`);fieldset.append(legend);const bnPrompt=create("p","reading-prompt-bn",question.promptBn);bnPrompt.lang="bn";fieldset.append(bnPrompt);const options=create("div","reading-options");question.options.forEach((option,oIndex)=>{const label=document.createElement("label"),input=document.createElement("input");input.type="radio";input.name=`reading-${qIndex}`;input.value=String(oIndex);input.checked=answers[qIndex]===oIndex;input.disabled=checked;input.addEventListener("change",()=>{answers[qIndex]=oIndex;renderText();});label.append(input,create("span","",option));options.append(label);});fieldset.append(options);if(checked){const correct=answers[qIndex]===question.answer,feedback=create("div","reading-question-feedback");feedback.append(create("strong","",correct?"✓ Correct":"✕ Not quite"));if(!correct)feedback.append(create("p","",`Your answer: ${answers[qIndex]===null||answers[qIndex]===undefined?"Unanswered":question.options[answers[qIndex]]}`),create("p","reading-correct-answer",`Correct: ${question.options[question.answer]}`));feedback.append(create("p","",question.explanationEn));const bn=create("p","reading-explanation-bn",question.explanationBn);bn.lang="bn";feedback.append(bn,create("small","",`Evidence: “${question.evidence}”`));fieldset.append(feedback);}questions.append(fieldset);});layout.append(questions);form.append(header,track,layout);
  if(!checked){const check=create("button","reading-check","Check Answers");check.type="button";check.disabled=answers.filter(value=>value!==null&&value!==undefined).length!==text.questions.length;check.addEventListener("click",checkText);form.append(check);}else{const next=create("button","reading-next",index===session.length-1?"View Session Results":"Next Text →");next.type="button";next.addEventListener("click",()=>{if(index===session.length-1)showResults();else{index++;answers=[];checked=false;renderText();scrollTo({top:document.querySelector(".practice-workspace")?.offsetTop||0,behavior:"smooth"});}});form.append(next);}
  $("answeredCount").textContent=`Text ${index+1} of ${session.length} · ${answers.filter(value=>value!==null&&value!==undefined).length}/${text.questions.length} answered`;$("progressFill").style.width=`${index/session.length*100}%`;
 }
 function checkText(){if(checked)return;const text=session[index];checked=true;text.questions.forEach((question,qIndex)=>{const correct=answers[qIndex]===question.answer,row={text,question,selected:answers[qIndex],correct};results.push(row);if(!correct)mistakes.push(row);});const skill=progress.skillStats[text.skill]||{texts:0,attempted:0,correct:0};const correctCount=text.questions.filter((question,qIndex)=>answers[qIndex]===question.answer).length;progress.skillStats[text.skill]={texts:skill.texts+1,attempted:skill.attempted+text.questions.length,correct:skill.correct+correctCount};const old=progress.textStats[text.id]||{attempts:0,correctQuestions:0};progress.textStats[text.id]={attempts:old.attempts+1,correctQuestions:(old.correctQuestions||0)+correctCount,totalQuestions:text.questions.length,lastPractised:new Date().toISOString()};progress.textsCompleted=(progress.textsCompleted||0)+1;progress.questionsAttempted=(progress.questionsAttempted||0)+text.questions.length;progress.questionsCorrect=(progress.questionsCorrect||0)+correctCount;persist();renderText();}
 function sessionBreakdown(){return Object.keys(A1_READING_SKILLS).map(skill=>{const rows=results.filter(row=>row.text.skill===skill);return{skill,total:rows.length,correct:rows.filter(row=>row.correct).length};}).filter(row=>row.total);}
 function weakSkills(){return Object.entries(progress.skillStats).filter(([,stat])=>stat.attempted>=6&&stat.correct/stat.attempted<.8).sort((a,b)=>a[1].correct/a[1].attempted-b[1].correct/b[1].attempted).slice(0,2).map(([skill])=>skill);}
 function outcome(percent){if(percent>=80)return["Strong Reading Round","Excellent. You understood most details across these A1 reading texts."];if(percent>=60)return["Good Progress","Good progress. Review the evidence for missed questions and practise your weaker reading areas."];return["Keep Reading","Review the texts, evidence and vocabulary help before trying another session."];}
 function showResults(){const score=results.filter(row=>row.correct).length,percent=Math.round(score/results.length*100),[label,message]=outcome(percent);if(!resultSaved){progress.sessionsCompleted=(progress.sessionsCompleted||0)+1;progress.bestPercent=Math.max(progress.bestPercent||0,percent);progress.lastPercent=percent;progress.lastSessionIds=session.map(text=>text.id);resultSaved=true;persist();}$("practiceForm").hidden=true;const result=$("practiceResult");result.hidden=false;result.replaceChildren(create("span","",currentMode==="weak"?"Weak Reading Practice Complete":"Reading Session Complete"),create("strong","",`${score}/${results.length}`),create("p","reading-result-label",`${percent}% · ${label}`),create("p","",`${session.length} / ${session.length} texts completed`),create("p","",message));const grid=create("div","reading-breakdown");sessionBreakdown().forEach(row=>{const card=create("div",row.correct/row.total>=.8?"is-strong":"needs-review");card.append(create("strong","",A1_READING_SKILLS[row.skill]),create("span","",`${row.correct} / ${row.total}`));grid.append(card);});const breakdown=sessionBreakdown(),strong=breakdown.filter(row=>row.correct/row.total>=.8).map(row=>A1_READING_SKILLS[row.skill]),review=breakdown.filter(row=>row.correct/row.total<.8).map(row=>A1_READING_SKILLS[row.skill]);const areas=create("div","reading-areas");areas.append(create("p","",`Strong Reading Areas: ${strong.join(", ")||"Keep building"}`),create("p","",`Needs More Practice: ${review.join(", ")||"None this round"}`));const actions=create("div","reading-result-actions"),reviewButton=create("button","","Review Reading Mistakes");reviewButton.type="button";reviewButton.disabled=!mistakes.length;reviewButton.addEventListener("click",showMistakes);const focus=weakSkills().length?weakSkills():breakdown.filter(row=>row.correct/row.total<.8).slice(0,2).map(row=>row.skill);const weak=create("button","","Practice Weak Areas");weak.type="button";weak.disabled=!focus.length;weak.addEventListener("click",()=>startSession(focus));const again=create("button","","New Reading Session");again.type="button";again.addEventListener("click",()=>startSession());const back=create("a","challenge-back-link","Back to Practice Center");back.href="../a1/#exercises";actions.append(reviewButton,weak,again,back);result.append(grid,areas,actions);result.scrollIntoView({behavior:"smooth",block:"start"});}
 function showMistakes(){const result=$("practiceResult");result.replaceChildren(create("span","","Review Reading Mistakes"),create("h2","",`${mistakes.length} questions to review`));const list=create("div","reading-review-list"),groups=new Map();mistakes.forEach(row=>{if(!groups.has(row.text.id))groups.set(row.text.id,{text:row.text,rows:[]});groups.get(row.text.id).rows.push(row);});groups.forEach(group=>{const card=create("article","reading-review-card");card.append(create("span","reading-format",formatLabel(group.text.format)),create("h3","",group.text.title));const text=create("p","reading-german-text",group.text.text);text.lang="de";card.append(text);group.rows.forEach(row=>{const bn=create("p","reading-explanation-bn",row.question.explanationBn);bn.lang="bn";const question=create("section","reading-review-question");question.append(create("h4","",row.question.promptEn),create("p","",`Your answer: ${row.question.options[row.selected]}`),create("p","reading-correct-answer",`Correct: ${row.question.options[row.question.answer]}`),create("p","",row.question.explanationEn),bn,create("small","",`Evidence: “${row.question.evidence}”`));card.append(question);});const link=create("a","challenge-topic-link","Review related topic →");link.href=`../library-topic/?level=A1&topic=${group.text.relatedTopic}`;card.append(link);list.append(card);});const back=create("button","","Back to Results");back.type="button";back.addEventListener("click",showResults);result.append(list,back);}
 startSession();
}
