import { initLevelPage } from "./level-page.js";
import { initAuthGate } from "./auth-gate.js";
const LEVELS=["A1","A2","B1","B2"];
const CATEGORIES={
 grammar:{label:"Grammar Notes",icon:"fa-file-lines",files:[["grammar-reference","Grammar Reference","Core rules, structures and examples"],["verb-and-sentence-guide","Verb and Sentence Guide","Verb forms, position and sentence patterns"],["grammar-quick-review","Grammar Quick Review","A compact revision checklist"]]},
 vocabulary:{label:"Vocabulary Books",icon:"fa-book-open",files:[["everyday-vocabulary","Everyday Vocabulary","High-value words for daily communication"],["topic-word-list","Topic Word List","Organized vocabulary with English meanings"],["useful-expressions","Useful Expressions","Natural phrases for common situations"]]},
 worksheets:{label:"Practice Worksheets",icon:"fa-pen-to-square",files:[["grammar-worksheet","Grammar Worksheet","Printable tasks with an answer key"],["reading-worksheet","Reading Worksheet","A graded text and comprehension questions"],["mixed-practice","Mixed Practice Worksheet","Grammar, vocabulary and writing practice"]]},
 flashcards:{label:"Printable Flashcards",icon:"fa-clone",files:[["daily-life-flashcards","Daily Life Flashcards","Cut-out cards for everyday vocabulary"],["verbs-flashcards","Verb Flashcards","Useful verbs and sentence prompts"],["expressions-flashcards","Expression Flashcards","Reusable speaking expressions"]]}
};
const p=new URLSearchParams(location.search), raw=(p.get("level")||"A1").toUpperCase(), level=LEVELS.includes(raw)?raw:"A1", selected=CATEGORIES[p.get("category")]?p.get("category"):"all";
const categories=selected==="all"?Object.keys(CATEGORIES):[selected];
document.title=`Download Center | Rafis Sprachwelt ${level}`;document.getElementById("downloadBranding").textContent=`Rafis Sprachwelt - ${level}`;document.getElementById("downloadLevel").textContent=`${level} Resources`;document.getElementById("downloadBack").href=`${level.toLowerCase()}.html#resources`;
document.getElementById("downloadTabs").innerHTML=`<a class="${selected==='all'?'active':''}" href="download-center.html?level=${level}">All</a>`+Object.entries(CATEGORIES).map(([key,value])=>`<a class="${selected===key?'active':''}" href="download-center.html?level=${level}&amp;category=${key}">${value.label}</a>`).join("");
const files=categories.flatMap(key=>CATEGORIES[key].files.map(file=>({key,icon:CATEGORIES[key].icon,...{slug:file[0],title:file[1],description:file[2]}})));
document.getElementById("categoryLabel").textContent=selected==="all"?"Complete library":CATEGORIES[selected].label;document.getElementById("categoryTitle").textContent=selected==="all"?`${level} Study Library`:CATEGORIES[selected].label;document.getElementById("fileCount").textContent=`${files.length} PDF${files.length===1?'':'s'}`;
document.getElementById("downloadGrid").innerHTML=files.map(file=>`<article class="download-card"><span><i class="fa-solid ${file.icon}"></i></span><small>${level} · PDF</small><h3>${file.title}</h3><p>${file.description}.</p><div><a href="../assets/pdfs/${level.toLowerCase()}/${file.key}/${file.slug}.pdf" target="_blank">Preview</a><a class="download-file" href="../assets/pdfs/${level.toLowerCase()}/${file.key}/${file.slug}.pdf" download>Download <i class="fa-solid fa-download"></i></a></div></article>`).join("");initAuthGate();initLevelPage();
