/* Editable Practice Center content. Each bank is calibrated to its CEFR level. */
export const PRACTICE_TYPES = {
  grammar: { title: "Grammar Challenge", label: "Grammar", instruction: "Choose the grammatically correct answer." },
  flashcards: { title: "Vocabulary Trainer", label: "Vocabulary", instruction: "Choose the German word or expression that matches the prompt." },
  matching: { title: "Match the Words", label: "Vocabulary", instruction: "Match each German expression with its correct meaning." },
  listening: { title: "Listen & Choose", label: "Listening", instruction: "Play each sentence and choose what you hear or understand.", audio: true },
  reading: { title: "Reading Comprehension", label: "Reading", instruction: "Read the short text and select the best answer." },
  writing: { title: "Sentence Builder", label: "Writing", instruction: "Choose the sentence with correct spelling and word order." },
  speaking: { title: "Speaking Practice", label: "Speaking", instruction: "Choose the most natural response for each situation." },
  mock: { title: "Goethe-Style Practice Test", label: "Exam Practice", instruction: "Complete this mixed-skills practice set under test conditions." }
};

const q = (prompt, options, answer, note, speech = "") => ({ prompt, options, answer, note, speech });

export const LEVEL_BANKS = {
  A1: {
    grammar: [q("___ Name ist Sara.",["Mein","Meine","Meinen"],0,"Name is masculine: mein Name."),q("Wir ___ in Berlin.",["wohnt","wohnen","wohnst"],1,"Wir takes the -en verb ending."),q("Ich kaufe ___ Apfel.",["ein","eine","einen"],2,"Apfel is masculine and accusative."),q("___ du Deutsch?",["Sprechen","Sprichst","Sprecht"],1,"Du takes sprichst." )],
    vocabulary: [q("What is ‘the train station’ in German?",["der Bahnhof","die Küche","das Rathaus"],0,"Der Bahnhof means train station."),q("die Familie",["family","company","holiday"],0,"Die Familie means family."),q("What is ‘expensive’?",["billig","teuer","langsam"],1,"Teuer means expensive."),q("der Mittwoch",["Wednesday","Monday","weekend"],0,"Mittwoch is Wednesday.")],
    communication: [q("Someone says: Guten Morgen!",["Guten Morgen!","Gute Nacht!","Entschuldigung!"],0,"Return the same morning greeting."),q("Wie heißen Sie?",["Ich komme aus Dhaka.","Ich heiße Rafi.","Mir geht es gut."],1,"The question asks your name."),q("Was kostet das?",["Es kostet fünf Euro.","Es ist Montag.","Ich bin zwanzig."],0,"Answer with a price."),q("Danke schön!",["Bitte schön!","Auf Wiedersehen!","Keine Ahnung."],0,"Bitte is the natural response.")],
    reading: [q("Text: Lena wohnt in Bonn und arbeitet in einem Café. Wo wohnt Lena?",["In Berlin","In Bonn","In Wien"],1,"The text says ‘wohnt in Bonn’."),q("Text: Der Kurs beginnt um neun Uhr. Wann beginnt er?",["Um 8 Uhr","Um 9 Uhr","Um 10 Uhr"],1,"Neun Uhr is 9:00."),q("Text: Paul kauft Brot und Milch. Was kauft er?",["Obst","Brot und Milch","Kaffee"],1,"Both items are named directly."),q("Text: Am Sonntag bleibt Mia zu Hause. Was macht Mia?",["Sie reist.","Sie arbeitet.","Sie bleibt zu Hause."],2,"The final phrase gives the answer.")]
  },
  A2: {
    grammar: [q("Gestern ___ ich lange gearbeitet.",["habe","bin","werde"],0,"Arbeiten forms the perfect with haben."),q("Ich bleibe zu Hause, ___ ich krank bin.",["denn","weil","oder"],1,"Weil introduces a subordinate clause."),q("Kannst du ___ helfen?",["mich","mir","mein"],1,"Helfen requires the dative."),q("Der Film ist ___ als das Buch.",["spannend","spannender","am spannendsten"],1,"Als signals the comparative.")],
    vocabulary: [q("die Verspätung",["delay","departure","platform"],0,"Verspätung means delay."),q("What is ‘to make an appointment’?",["einen Termin vereinbaren","eine Reise absagen","Geld abheben"],0,"This is the standard expression."),q("die Unterkunft",["accommodation","information","experience"],0,"Unterkunft is a place to stay."),q("sich erholen",["to hurry","to recover/relax","to complain"],1,"Sich erholen means to recover or relax.")],
    communication: [q("You cannot attend an appointment.",["Ich möchte den Termin absagen.","Ich hätte gern die Rechnung.","Ich steige hier aus."],0,"Absagen means cancel."),q("Wie war dein Urlaub?",["Seit zwei Wochen.","Er war sehr erholsam.","Nach Italien."],1,"The question asks for an evaluation."),q("Could you speak more slowly?",["Könnten Sie bitte langsamer sprechen?","Darf ich hier bezahlen?","Wann fährt der Zug ab?"],0,"This is a polite request."),q("Was würdest du empfehlen?",["Ich empfehle die Suppe.","Ich habe reserviert.","Es tut mir leid."],0,"Recommend an option.")],
    reading: [q("Text: Wegen Bauarbeiten fährt der Bus heute nicht. Warum fällt der Bus aus?",["Wegen des Wetters","Wegen Bauarbeiten","Wegen eines Unfalls"],1,"The reason is stated first."),q("Text: Nora sucht eine Wohnung mit Balkon, höchstens 700 Euro. Was ist wichtig?",["Ein Garten","Ein Balkon und der Preis","Drei Schlafzimmer"],1,"Both requirements appear in the text."),q("Text: Bitte melden Sie sich bis Freitag an. Was muss man tun?",["Am Freitag kommen","Vor Freitag bezahlen","Sich spätestens Freitag anmelden"],2,"Bis Freitag gives the deadline."),q("Text: Das Geschäft öffnet samstags erst um zehn. Wann öffnet es?",["Um 8","Um 9","Um 10"],2,"Erst um zehn means not before 10.")]
  },
  B1: {
    grammar: [q("Wenn ich mehr Zeit hätte, ___ ich öfter lesen.",["werde","würde","wurde"],1,"Konjunktiv II uses würde here."),q("Das ist die Kollegin, mit ___ ich arbeite.",["die","der","deren"],1,"Mit requires dative; feminine relative pronoun der."),q("Obwohl es regnete, ___ wir spazieren.",["gingen","gegangen","gehen würden"],0,"A completed past action uses Präteritum here."),q("Die Aufgabe muss heute ___ werden.",["erledigen","erledigt","erledigte"],1,"Passive: participle + werden.")],
    vocabulary: [q("eine Entscheidung treffen",["to postpone a decision","to make a decision","to explain a decision"],1,"Treffen combines with Entscheidung."),q("zuverlässig",["reliable","temporary","suspicious"],0,"Zuverlässig means dependable."),q("What means ‘to take responsibility’?",["Verantwortung übernehmen","Rücksicht nehmen","in Anspruch nehmen"],0,"Übernehmen is used with Verantwortung."),q("die Voraussetzung",["requirement/prerequisite","consequence","exception"],0,"Voraussetzung is a condition required beforehand.")],
    communication: [q("Politely disagree in a discussion.",["Das ist falsch.","Ich sehe das etwas anders.","Das interessiert mich nicht."],1,"This expresses respectful disagreement."),q("Ask for clarification.",["Könnten Sie genauer erklären, was Sie damit meinen?","Würden Sie das vermeiden?","Darf ich widersprechen?"],0,"The sentence explicitly requests clarification."),q("Give a balanced opinion.",["Einerseits ist es praktisch, andererseits teuer.","Es ist auf jeden Fall perfekt.","Dazu sage ich nichts."],0,"Einerseits/andererseits balances two views."),q("Make a formal complaint.",["Ich möchte mich über die Lieferung beschweren.","Die Lieferung war komisch.","Schick das noch mal."],0,"This is appropriately formal.")],
    reading: [q("Text: Homeoffice spart Fahrzeit, kann jedoch den Austausch im Team erschweren. Welcher Nachteil wird genannt?",["Höhere Fahrtkosten","Weniger Austausch","Längere Arbeitszeit"],1,"The contrast after jedoch names the disadvantage."),q("Text: Die Veranstaltung wurde aufgrund geringer Nachfrage verschoben. Warum?",["Der Raum war belegt.","Es gab zu wenig Interesse.","Der Referent war krank."],1,"Geringe Nachfrage means insufficient interest."),q("Text: Bewerbungen, die nach dem 15. Mai eingehen, werden nicht berücksichtigt. Was gilt?",["Späte Bewerbungen zählen nicht.","Alle bekommen eine Antwort.","Die Frist beginnt am 15. Mai."],0,"After the deadline, applications are excluded."),q("Text: Trotz Kritik hält die Stadt an ihrem Verkehrskonzept fest. Was macht die Stadt?",["Sie ändert alles.","Sie beendet das Projekt.","Sie behält den Plan bei."],2,"An etwas festhalten means retain it.")]
  },
  B2: {
    grammar: [q("Die Maßnahme zielt darauf ab, den Verbrauch ___ .",["senken","zu senken","gesenkt"],1,"Darauf abzielen takes an infinitive clause with zu."),q("Kaum ___ die Sitzung begonnen, kam es zum Streit.",["hatte","war","wurde"],0,"Past perfect marks the earlier event."),q("Der Bericht, ___ Ergebnisse umstritten sind, wird geprüft.",["dessen","deren","dem"],0,"Bericht is masculine; possessive relative pronoun dessen."),q("Es ist davon auszugehen, dass die Kosten ___ .",["steigen","gestiegen","zu steigen"],0,"Dass requires a finite verb at the end.")],
    vocabulary: [q("etwas in Frage stellen",["to confirm something","to question something","to postpone something"],1,"The phrase means to doubt or challenge."),q("nachhaltig",["sustainable","unavoidable","profitable"],0,"Nachhaltig means sustainable/lasting."),q("eine Entwicklung begünstigen",["to encourage a development","to reverse a development","to overlook a development"],0,"Begünstigen means favor or facilitate."),q("die Tragweite",["scope/significance","procedure","credibility"],0,"Tragweite describes the extent or consequences.")],
    communication: [q("Qualify a strong claim academically.",["Das ist immer so.","Vieles deutet darauf hin, dass …","Das weiß doch jeder."],1,"This presents evidence without overstating certainty."),q("Redirect a formal discussion.",["Kehren wir zur Ausgangsfrage zurück.","Das Thema ist langweilig.","Reden wir über etwas anderes."],0,"This is precise and appropriately formal."),q("Acknowledge and counter an argument.",["Zwar ist der Einwand berechtigt, dennoch …","Das stimmt überhaupt nicht.","Vielleicht, vielleicht nicht."],0,"Zwar … dennoch concedes before countering."),q("Express a nuanced conclusion.",["Zusammenfassend überwiegen die Vorteile, sofern …","Alles ist gut.","Es gibt nur Nachteile."],0,"The condition makes the conclusion nuanced.")],
    reading: [q("Text: Die Reform mag kurzfristig Kosten verursachen, dürfte sich langfristig jedoch auszahlen. Welche Bewertung trifft zu?",["Nur kurzfristig positiv","Langfristig vermutlich vorteilhaft","Grundsätzlich wirkungslos"],1,"Dürfte sich auszahlen signals a likely long-term benefit."),q("Text: Die Studie erlaubt keine kausalen Schlüsse, da lediglich Zusammenhänge erfasst wurden. Was ist die Einschränkung?",["Zu wenige Themen","Keine Ursache-Wirkung-Aussage","Fehlende Veröffentlichung"],1,"Correlation alone cannot establish causation."),q("Text: Der Vorschlag stieß parteiübergreifend auf Zustimmung. Was bedeutet das?",["Nur eine Partei stimmte zu.","Mehrere politische Lager unterstützten ihn.","Die Abstimmung wurde vertagt."],1,"Parteiübergreifend means across party lines."),q("Text: Die Autorin relativiert ihre These im letzten Abschnitt. Was tut sie?",["Sie formuliert sie differenzierter.","Sie wiederholt sie wörtlich.","Sie beweist sie endgültig."],0,"Relativieren means qualify or limit a claim.")]
  }
};

export function getQuestions(level, type) {
  const bank = LEVEL_BANKS[level] || LEVEL_BANKS.A1;
  if (type === "grammar" || type === "writing") return bank.grammar;
  if (type === "reading") return bank.reading;
  if (type === "flashcards" || type === "matching") return bank.vocabulary;
  if (type === "mock") return [bank.grammar[0], bank.vocabulary[1], bank.reading[2], bank.communication[3]];
  return bank.communication.map(item => type === "listening" ? { ...item, speech: item.prompt } : item);
}
