const topic = (id, title, level, en, bn, de, examples, mistakes, practice) => ({
  id, title, level, shortRuleEn: en, shortRuleBn: bn, simpleGermanRule: de,
  examples, commonMistakes: mistakes, practice
});

export const TUTOR_GRAMMAR_TOPICS = [
  topic("nominativ", "Nominativ", "A1", "The nominative marks the subject: the person or thing doing the action.", "Nominativ বাক্যের কর্তা বোঝায়—যে ব্যক্তি বা বস্তু কাজটি করে।", "Der Nominativ zeigt das Subjekt. Frage: Wer oder was?", ["Der Mann arbeitet.", "Das Kind spielt."], ["Do not choose a case only from word position; first find the subject."], ["Mark the subject: Die Frau kauft Brot."]),
  topic("akkusativ", "Akkusativ", "A1", "The accusative usually marks the direct object. Masculine der/ein changes to den/einen.", "Akkusativ সাধারণত সরাসরি কর্ম বোঝায়। পুংলিঙ্গ der/ein বদলে den/einen হয়।", "Der Akkusativ zeigt oft das direkte Objekt. Frage: Wen oder was?", ["Ich sehe den Mann.", "Sie kauft einen Apfel."], ["Feminine die/eine and neuter das/ein do not change in the accusative."], ["Choose: Ich brauche ein/einen Stift."]),
  topic("dativ", "Dativ", "A1/A2", "The dative often marks a recipient and follows prepositions such as mit, nach, aus, zu and von.", "Dativ প্রায়ই প্রাপক বোঝায় এবং mit, nach, aus, zu, von-এর পরে ব্যবহৃত হয়।", "Der Dativ zeigt oft den Empfänger. Frage: Wem?", ["Ich helfe dem Kind.", "Sie fährt mit der Bahn."], ["Use wem, not wen, to ask for a dative object."], ["Complete: Ich spreche mit ___ Lehrer."]),
  topic("definite-articles", "der / die / das", "A1", "German nouns have grammatical gender. Learn every noun together with its article.", "জার্মান বিশেষ্যের ব্যাকরণগত লিঙ্গ আছে। প্রতিটি শব্দ article-সহ শিখুন।", "Lerne jedes Nomen mit Artikel: der, die oder das.", ["der Tisch", "die Lampe", "das Buch"], ["Natural gender does not reliably predict grammatical gender."], ["Add der, die or das to five nouns."]),
  topic("indefinite-articles", "ein / eine", "A1", "Use ein for masculine and neuter nominative nouns; use eine for feminine nouns.", "Nominativ-এ পুংলিঙ্গ ও ক্লীবলিঙ্গে ein, স্ত্রীলিঙ্গে eine হয়।", "Im Nominativ: ein Mann, eine Frau, ein Kind.", ["Das ist ein Hund.", "Das ist eine Tasche."], ["There is no indefinite article for an unspecified plural."], ["Choose ein/eine: ___ Wohnung, ___ Auto."]),
  topic("personal-pronouns", "Personalpronomen", "A1", "Personal pronouns replace nouns: ich, du, er, sie, es, wir, ihr, sie/Sie.", "Personalpronomen বিশেষ্যের বদলে ব্যবহৃত হয়: ich, du, er, sie, es ইত্যাদি।", "Personalpronomen ersetzen Personen oder Sachen.", ["Mia lernt. Sie lernt.", "Tom und ich arbeiten. Wir arbeiten."], ["Formal Sie is always capitalized."], ["Replace: Paul kommt. → ___ kommt."]),
  topic("possessive-articles", "Possessivartikel", "A1/A2", "Possessive articles show ownership and take endings similar to ein: mein, dein, sein, ihr, unser, euer, Ihr.", "Possessivartikel মালিকানা বোঝায় এবং ein-এর মতো ending নেয়।", "Possessivartikel zeigen Zugehörigkeit: mein Buch, meine Tasche.", ["Das ist mein Bruder.", "Wo ist deine Jacke?"], ["The ending agrees with the following noun, not the owner."], ["Complete: Anna sucht ___ Schlüssel."]),
  topic("praesens", "Präsens", "A1", "The present tense describes current actions, habits and often planned future events.", "Präsens বর্তমান কাজ, অভ্যাস এবং কখনও পরিকল্পিত ভবিষ্যৎ বোঝায়।", "Im Präsens wird das Verb passend zum Subjekt konjugiert.", ["Ich lerne Deutsch.", "Morgen fahre ich nach Bonn."], ["The verb ending must agree with the subject."], ["Conjugate lernen with ich, du and wir."]),
  topic("perfekt", "Perfekt", "A1/A2", "The conversational past uses haben or sein plus Partizip II. The participle normally goes to the end.", "কথ্য অতীতে haben/sein + Partizip II হয়; Partizip সাধারণত শেষে যায়।", "Perfekt: haben/sein + Partizip II am Satzende.", ["Ich habe gearbeitet.", "Wir sind gefahren."], ["Movement does not always guarantee sein; learn the auxiliary with the verb."], ["Change: Ich lerne. → Perfekt."]),
  topic("modal-verbs", "Modalverben", "A1/A2", "A modal verb is conjugated in position two; the main infinitive goes to the end.", "Modalverb দ্বিতীয় স্থানে conjugate হয়; মূল infinitive শেষে যায়।", "Modalverb auf Position zwei, Infinitiv am Ende.", ["Ich kann gut schwimmen.", "Du musst heute arbeiten."], ["Do not conjugate both verbs in a simple modal construction."], ["Build a sentence with können and lernen."]),
  topic("separable-verbs", "Trennbare Verben", "A1/A2", "In a main clause, the separable prefix moves to the end. In the infinitive it stays attached.", "Main clause-এ separable prefix শেষে যায়; infinitive-এ যুক্ত থাকে।", "Im Hauptsatz steht die Vorsilbe am Ende.", ["Ich stehe um sieben Uhr auf.", "Wir kaufen heute ein."], ["Do not separate the prefix in a subordinate clause with weil."], ["Rewrite: aufstehen → Ich ___ früh ___."]),
  topic("negation", "nicht vs. kein", "A1/A2", "Kein negates an indefinite noun; nicht negates verbs, qualities or specific information.", "kein অনির্দিষ্ট বিশেষ্যকে নাকচ করে; nicht কাজ, গুণ বা নির্দিষ্ট তথ্যকে নাকচ করে।", "Kein steht bei Nomen; nicht verneint andere Satzteile.", ["Ich habe kein Auto.", "Das Auto ist nicht teuer."], ["Do not use kein before a definite article."], ["Choose nicht/kein: Ich trinke ___ Kaffee."]),
  topic("two-way-prepositions", "Wechselpräpositionen", "A2", "Two-way prepositions take accusative for destination (wohin?) and dative for location (wo?).", "Wechselpräposition গন্তব্যে Akkusativ (wohin?), অবস্থানে Dativ (wo?) নেয়।", "Wohin? + Akkusativ. Wo? + Dativ.", ["Ich gehe in die Küche.", "Ich bin in der Küche."], ["Movement alone is not enough; decide whether there is a destination."], ["Choose the case: Das Bild hängt an ___ Wand."]),
  topic("weil", "weil", "A2", "Weil introduces a reason and sends the conjugated verb to the end of its clause.", "weil কারণ বোঝায় এবং conjugated verb clause-এর শেষে পাঠায়।", "Nach weil steht das konjugierte Verb am Ende.", ["Ich bleibe zu Hause, weil ich krank bin."], ["Do not keep the verb in normal position two after weil."], ["Join two sentences with weil."]),
  topic("dass", "dass", "A2", "Dass introduces a subordinate content clause; its conjugated verb goes to the end.", "dass একটি subordinate content clause শুরু করে; verb শেষে যায়।", "Im dass-Satz steht das Verb am Ende.", ["Ich weiß, dass er heute kommt."], ["Dass has double s; das can be an article or pronoun."], ["Complete: Ich glaube, dass ..."]),
  topic("wenn", "wenn", "A2", "Wenn means if or whenever/when for repeated and present/future situations. The verb goes to the end.", "wenn শর্ত বা বারবার/বর্তমান-ভবিষ্যতের 'যখন' বোঝায়; verb শেষে যায়।", "Wenn leitet einen Nebensatz ein; das Verb steht am Ende.", ["Wenn es regnet, bleibe ich zu Hause."], ["For a single completed past event, als is usually used instead."], ["Write one real condition with wenn."]),
  topic("denn", "denn", "A2", "Denn gives a reason but connects two main clauses, so normal word order remains.", "denn কারণ বোঝায়, তবে দুটি main clause যুক্ত করে; স্বাভাবিক word order থাকে।", "Nach denn bleibt die normale Hauptsatzstellung.", ["Ich gehe schlafen, denn ich bin müde."], ["Do not send the verb to the end after denn."], ["Join two clauses with denn."]),
  topic("deshalb", "deshalb", "A2", "Deshalb refers to a result. When it begins a clause, the conjugated verb follows immediately.", "deshalb ফল বোঝায়; clause-এর শুরুতে থাকলে conjugated verb সঙ্গে সঙ্গে আসে।", "Deshalb steht auf Position eins; das Verb folgt auf Position zwei.", ["Es regnet. Deshalb bleibe ich zu Hause."], ["Do not treat deshalb like weil."], ["Write a cause and a result with deshalb."]),
  topic("word-order", "Word Order", "A1/A2", "In a German statement, the conjugated verb normally occupies position two.", "জার্মান statement-এ conjugated verb সাধারণত দ্বিতীয় স্থানে থাকে।", "Im Aussagesatz steht das konjugierte Verb auf Position zwei.", ["Heute lerne ich Deutsch.", "Ich lerne heute Deutsch."], ["Position one can contain several words as one unit."], ["Begin with Heute: Ich arbeite heute zu Hause."]),
  topic("tmp", "Time–Manner–Place", "A2", "A useful neutral order for adverbials is time, manner, place—not an absolute rule.", "Adverbial-এর একটি সাধারণ নিরপেক্ষ ক্রম হলো সময়–পদ্ধতি–স্থান; এটি কঠোর নিয়ম নয়।", "Eine häufige Reihenfolge ist Zeit – Art – Ort.", ["Ich fahre morgen mit dem Bus nach Berlin."], ["Treat this as a helpful default, not an unbreakable law."], ["Order: nach Hamburg / morgen / mit dem Zug."]),
  topic("adjective-basics", "Adjective Basics", "A2", "Before a noun, German adjectives usually take an ending. After sein/werden/bleiben, they normally have no ending.", "বিশেষ্যের আগে adjective সাধারণত ending নেয়; sein/werden/bleiben-এর পরে সাধারণত ending হয় না।", "Vor dem Nomen hat das Adjektiv eine Endung; nach sein meist nicht.", ["Das ist ein gutes Buch.", "Das Buch ist gut."], ["Do not add an ending to a predicate adjective after sein."], ["Choose: Das ist ein alt/altes Haus."]),
  topic("comparison", "Comparative & Superlative", "A2", "The comparative usually adds -er and uses als. The superlative often uses am ...-sten.", "Comparative সাধারণত -er ও als ব্যবহার করে; superlative প্রায়ই am ...-sten হয়।", "Komparativ: -er + als. Superlativ: am ...-sten.", ["Berlin ist größer als Bonn.", "Heute ist es am wärmsten."], ["Use als for unequal comparison; use wie for equality."], ["Compare schnell and langsam."])
];
